User management
Zenrac/jhipster-dotnetcore pull request #6
Opened 2020-12-18 12:37 UTC by Thomas-Julien-SAHUT

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

2020-12-18 16:13 UTC, Zenrac requested changes
MyEntity doesnt exist anymore. You dont handled conflicts correctly

2020-12-18 16:13 UTC, Zenrac commented on generators/client/templates/xamarin/src/Project.Client.Xamarin.Core/Services/AuthenticationService.cs.ejs
> +        public JwtToken JwtToken { get; set; }
Shouldn't be public

2020-12-18 16:13 UTC, Zenrac commented on generators/client/templates/xamarin/src/Project.Client.Xamarin.Core/Services/IAuthenticationService.cs.ejs
> +        JwtToken JwtToken { get;}
Don't add this to interface

2020-12-18 16:13 UTC, Zenrac commented on generators/client/templates/xamarin/src/Project.Client.Xamarin.Core/Services/UserEntityService.cs.ejs
> +        protected JwtToken JwtToken { get; set; }
Same

2020-12-18 16:13 UTC, Zenrac commented on generators/client/templates/xamarin/src/Project.Client.Xamarin.Core/Services/UserEntityService.cs.ejs
> +            if (JwtToken != null)
Same

2020-12-18 16:13 UTC, Zenrac commented on generators/client/templates/xamarin/src/Project.Client.Xamarin.Core/Services/UserEntityService.cs.ejs
> +            _httpClient.BaseAddress = new Uri(Configuration.BaseUri);
Same

2020-12-18 16:13 UTC, Zenrac commented on generators/client/templates/xamarin/src/Project.Client.Xamarin.Core/ViewModels/MenuViewModel.cs.ejs
> +        public IMvxCommand ShowMyEntitiesCommand => new MvxAsyncCommand(ShowMyEntitiesCommandClicked);
Remove this

2020-12-18 16:13 UTC, Zenrac commented on generators/client/templates/xamarin/src/Project.Client.Xamarin.Core/ViewModels/MenuViewModel.cs.ejs
> +        private async Task ShowMyEntitiesCommandClicked()
Remove this

2020-12-18 16:13 UTC, Zenrac commented on generators/client/templates/xamarin/src/Project.Client.Xamarin.Core/ViewModels/MenuViewModel.cs.ejs
> +            await _navigationService.Navigate<MyEntityViewModel>();
MyEntityViewModel doesnt exist anymore

2020-12-18 16:13 UTC, Zenrac commented on generators/client/templates/xamarin/src/Project.Client.Xamarin.Core/Views/MenuPage.xaml.ejs
> +                <Grid HorizontalOptions="FillAndExpand" VerticalOptions="StartAndExpand" Padding="8" BackgroundColor="LightBlue" IsVisible="{Binding IsConnected}">
Remove this

2020-12-18 16:13 UTC, Zenrac commented on generators/client/templates/xamarin/src/Project.Client.Xamarin.Core/Views/MenuPage.xaml.ejs
> +                        <TapGestureRecognizer Tapped="ToggleClicked" Command="{Binding ShowMyUsersCommand}" CommandParameter="TODO"/>
Remove CommandParameter

2020-12-18 16:13 UTC, Zenrac commented on generators/client/templates/xamarin/test/Project.Client.Test/Pages/TestPages/MyEntityViewModelTest.cs.ejs
> +    public class MyEntityViewModelTest : MvxIoCSupportingTest
MyEntity doesnt exist anymore

2020-12-18 17:19 UTC, Thomas-Julien-SAHUT commented on generators/client/templates/xamarin/src/Project.Client.Xamarin.Core/ViewModels/MenuViewModel.cs.ejs
> +        private async Task ShowMyEntitiesCommandClicked()
Why ?

2020-12-18 17:20 UTC, Thomas-Julien-SAHUT commented on generators/client/templates/xamarin/src/Project.Client.Xamarin.Core/Views/MenuPage.xaml.ejs
> +                        <TapGestureRecognizer Tapped="ToggleClicked" Command="{Binding ShowMyUsersCommand}" CommandParameter="TODO"/>
Why ?

2020-12-18 17:41 UTC, Zenrac commented on generators/client/templates/xamarin/src/Project.Client.Xamarin.Core/Views/MenuPage.xaml.ejs
> +                        <TapGestureRecognizer Tapped="ToggleClicked" Command="{Binding ShowMyUsersCommand}" CommandParameter="TODO"/>
Never used

2020-12-18 17:41 UTC, Zenrac commented on generators/client/templates/xamarin/src/Project.Client.Xamarin.Core/ViewModels/MenuViewModel.cs.ejs
> +        private async Task ShowMyEntitiesCommandClicked()
MyEntity doesnt exist anymore

2020-12-18 17:42 UTC, Zenrac commented on generators/client/templates/xamarin/src/Project.Client.Xamarin.Core/App.cs.ejs
> +            var myEntityService = new AbstractEntityService<AbstractEntityModel>(httpClient, "api/myentities");
Remove this

2020-12-19 02:21 UTC, Zenrac commented on generators/client/files-xamarin.js
> +                    file: 'Project.Client.Test/Pages/TestPages/MyEntityViewModelTest.cs',
Doesnt exist anymore

2020-12-19 02:21 UTC, Zenrac commented on generators/client/templates/xamarin/src/Project.Client.Xamarin.Core/Project.Client.Xamarin.Core.csproj.ejs
> +      <DependentUpon>MyEntityView.xaml</DependentUpon>
Doesnt exist

2020-12-19 02:22 UTC, Zenrac commented on generators/client/templates/xamarin/test/Project.Client.Test/Pages/TestPages/MyEntityViewModelTest.cs.ejs
> +    public class MyAbstractEntityViewModelTest : MvxIoCSupportingTest
MyEntityView doesnt exist too

2020-12-26 22:32 UTC, nicolas63 commented
@Zenrac any updates ?

2022-04-02 17:43 UTC, closed without merging